Add unique ID filter to Twig
forumone/gesso pull request #323
Opened 2020-01-25 22:47 UTC by kmonahan

Drupal 8 includes [Html::getUniqueId](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Html.php/function/Html%3A%3AgetUniqueId/8.2.x), which ensures that IDs aren't repeated on a page. This PR makes that functionality available as a Twig filter. For Pattern Lab, a unique ID is generated via the uniqid() function.

The typical use case for this is when you need to include an ID in multiple places in a pattern, such as in another element's ARIA attribute (as in the breadcrumbs pattern, which I updated here to use the new filter) or in a data attribute, particularly where the component might be used multiple times on a page. I usually find myself needing this with accordions.

2020-01-27 16:18 UTC, dcmouyard requested changes
Everything looks good to me, except for the ID variable.

2020-01-27 16:18 UTC, dcmouyard commented on source/_patterns/04-components/breadcrumb/breadcrumb.twig
> +{% set breadcrumb_label = 'breadcrumb-label'|unique_id %}
I think we should rename this variable to `breadcrumb_id` to make its purpose clear.

2020-01-27 16:21 UTC, dcmouyard commented
Should we also add this function to the pager label in `source/_patterns/04-components/pager/pager.twig` and `source/_patterns/04-components/pager/pager--mini/pager--mini.twig`?

2020-01-31 15:29 UTC, kmonahan commented
@dcmouyard , changes made.

2020-01-31 17:17 UTC, dcmouyard approved these changes
Looks good to me 👍

2020-01-31 20:41 UTC, merged