Consistent classes variable
forumone/gesso pull request #398
Opened 2020-09-30 17:36 UTC by dcmouyard

Fixes #354. This PR updates all classes-related twig variable names to be consistent and adds modifier_classes to most components"

2020-10-01 15:51 UTC, coreylafferty requested changes

2020-10-01 15:51 UTC, coreylafferty commented on source/_patterns/04-components/skiplinks/skiplinks.twig
>  <div class="skiplinks">
Need to output the classes var here

2020-10-01 15:51 UTC, coreylafferty commented on source/_patterns/04-components/site-slogan/site-slogan.twig
>  <span class="site-slogan">{{ site_slogan }}</span>
need to output the classes var here

2020-10-01 15:51 UTC, coreylafferty commented on source/_patterns/04-components/site-name/site-name.twig
>  <a class="site-name" href="{{ url }}" title="{{ 'Home'|t }}" rel="home">
need to output the classes var here

2020-10-01 19:02 UTC, dcmouyard commented
@coreylafferty The missing classes variables in those components should be fixed now.

2020-10-07 16:03 UTC, coreylafferty approved these changes

2020-10-07 16:04 UTC, merged