Update button styles
forumone/gesso pull request #48
Opened 2016-12-06 16:14 UTC by dcmouyard

This pull request depends on #46 being merged first.

2016-12-08 03:59 UTC, dcmouyard commented
I updated tje default button styles to match the [U.S. Web Design Standards](https://standards.usa.gov/colors/).

This pull request depends on #51 being merged first.

2016-12-08 23:13 UTC, dcmouyard commented
This pull request now depends on #46, #51, and #52 being merged first.

2016-12-11 16:11 UTC, coreylafferty requested changes

2016-12-11 16:11 UTC, coreylafferty commented on sass/partials/components/_button.scss
> +.button--danger {
Do we need all of these extra button styles?  Are they just examples or are any of these classes actually output in Drupal?

2016-12-11 19:03 UTC, dcmouyard commented on sass/partials/components/_button.scss
> +.button--danger {
The .button and .button--danger classes are the only ones that Drupal 8 outputs by default. The others are just examples based on what I’ve seen on projects the most. The designs for these button all come from https://standards.usa.gov/buttons/

2016-12-12 16:02 UTC, coreylafferty requested changes

2016-12-12 16:02 UTC, coreylafferty commented on sass/partials/components/_button.scss
> +.button--danger {
Can you add comments for the variants to that effect?  e.g., 

// Default Drupal button class output during the zombie apocalypse.
.button--danger {}

// Custom button class, included as an example. Not a default Drupal class name.
.button--secondary {}

// Size variations, included as examples.  Not default Drupal class names.
.button--lg {}
.button--sm {}

2016-12-12 16:26 UTC, dcmouyard commented
I broke out the button variants to a sub-folder and added comments explaining what they’re for.

2016-12-12 16:39 UTC, coreylafferty approved these changes

2016-12-12 16:39 UTC, merged