Update default typography
forumone/gesso pull request #52
Opened 2016-12-08 23:06 UTC by dcmouyard

I updated the default typography styles to match the [U.S. Web Design Standards](https://standards.usa.gov/typography/).

This pull request depends on #46 and #51 being merged first.

2016-12-11 16:12 UTC, coreylafferty requested changes

2016-12-11 16:12 UTC, coreylafferty commented on sass/partials/global/variables/_typography.scss
> +$base-line-height: 25.5px;
Why 25.5?

2016-12-11 16:12 UTC, coreylafferty commented on sass/partials/global/variables/_typography.scss
> +$vertical-spacing: $base-font-size;
Could a comment be added to explain what this variable is and how it's used?

2016-12-11 19:05 UTC, dcmouyard commented on sass/partials/global/variables/_typography.scss
> +$base-line-height: 25.5px;
25.5px for the line-height is just what the U.S. Web Design Standards use, which is the same as a line height of 1.5 for the body copy.

2016-12-11 19:06 UTC, dcmouyard commented on sass/partials/global/variables/_typography.scss
> +$vertical-spacing: $base-font-size;
Good idea. I’ll add a comment and push up a commit later.

2016-12-12 16:02 UTC, coreylafferty requested changes

2016-12-12 16:02 UTC, coreylafferty commented on sass/partials/global/variables/_typography.scss
> +$base-line-height: 25.5px;
Looking at the guidelines, they appear to set it 26px.  https://standards.usa.gov/typography/

Can we do that, or just set it to a unitless 1.5?

Also, do we need $base-line-height-ratio as a variable?  I don't see it being used (unless it's in another PR).

2016-12-12 17:11 UTC, dcmouyard commented
It turns out the html line-height was supposed to use the $base-line-height-ratio variable so that it’s unit-less.

The $base-line-height variable was often used as the default vertical spacing between elements, and we sometimes used multiples or half of that variable, so we needed a px-unit version of that variable. You can see an example in messages.scss.

Now that we have the vertical-spacing variable, though, perhaps we can remove the base-line-height-ratio variable and change the base-line-height variable to be unit-less. Then we could update messages.scss to use the vertical-spacing variable.

2016-12-12 17:20 UTC, coreylafferty commented
That sounds good to me.

2016-12-12 18:00 UTC, dcmouyard commented
I refactored the base-line-height usage.

2016-12-12 18:30 UTC, merged