adds focus for radio items
forumone/gesso pull request #751
Opened 2023-10-11 20:12 UTC by coreylafferty

Ran into this on a project. Radio items can individually be navigated with up/down arrow keys, but when tabbing through a form there is no focus state to indicate that you're inside the list of radio items. This fixes that, adding a focus state around the first item if none is selected when you tab to them.

2023-10-16 13:53 UTC, kmonahan requested changes

2023-10-16 13:53 UTC, kmonahan commented on source/03-components/form-item/form-item--radio/_form-item--radio.scss
> +      @include focus();
I'm confused here because the focus mixin already contains styling for the focus state. So what this will compile to is
```
.c-form-item__radio:focus-visible {
  outline: 2px solid transparent;
  outline-offset: 2px;
}

.c-form-item__radio:focus-visible:focus {
  outline-color: gesso-color(ui, generic, focus);
}

.c-form-item__radio:focus-visible:focus:not(:focus-visible) {
  outline-color: transparent
}
```
That seems a bit odd, especially the last part. Am I misunderstanding what's happening here? It seems to me like the focus mixin was in the correct spot originally but that some thing else needs to be added to fix the issue you noted.

2023-10-16 20:14 UTC, coreylafferty commented on source/03-components/form-item/form-item--radio/_form-item--radio.scss
> +      @include focus();
@kmonahan While my fix did technically work, I think you're right -- it's adding some CSS that doesn't make much sense and there's a simpler solution. I did some additional testing and realized it's the `outline: 0` that was causing the issue (no focus state using keyboard on radios), so I've updated the PR to just remove that.  Everything seems to work now.  To test, just open 'Form Item / Radios' in StoryBook and try to tab to them and get any of the radios to show a focus state without using your mouse.

2023-10-20 19:45 UTC, kmonahan approved these changes

2023-10-24 20:07 UTC, merged