Rtf list mixins
forumone/gesso pull request #800
Opened 2024-02-26 20:23 UTC by dcmouyard

2024-03-07 12:59 UTC, kmonahan commented
@dcmouyard If we're going to update these mixins (which makes sense to me), I'd suggest switching them to CSS logical properties, so we don't need the RTL check. That's the approach we took in Gesso for React: https://github.com/forumone/nextjs-project/blob/1.x/source/00-config/mixins/list.css

2024-03-07 13:00 UTC, kmonahan requested changes
I'm going to request changes, but if there's a reason you feel CSS logical properties aren't the right approach here, let's chat!

2024-03-19 19:23 UTC, dcmouyard commented
I like switching to logical properties, so I updated all of the list mixins to use that approach.

2024-03-20 13:05 UTC, kmonahan approved these changes

2024-03-26 14:37 UTC, merged